import {createConstants} from './../common/utils';

module.exports = createConstants(
        'USER_INFO_REQUEST', 'USER_INFO_ERROR', 'USER_INFO_SUCCESS', 'ISER_INFO_NA',
        'USER_INFO_SAVED_SUCCESS',
        'USER_AVATAR_SAVE_SUCCESS', 'USER_BIRTHDATE_SAVE_SUCCESS',
        'MENU_ITEM_SELECTED',
        'USER_NAME_SAVE_SUCCESS', 'USER_PHONE_SAVE_SUCCESS', 'USER_EMAIL_SAVE_SUCCESS', 'USER_DOCTOR_VISITED_SAVE_SUCCESS',
          'USER_LOGOUT',
        'JOURNALS_RECEIVED_SUCCESS',
        'SAVE_ACTIVITY_IMAGE_SUCCESS', 'USER_AVATAR_SAVE_SUCCESS', 'EDIT_JOURNAL_SUCCESS', 'DELETE_JOURNAL_SUCCESS', 'FILTER_JOURNAL_FEELING_SUCCESS', 'FILTER_JOURNAL_DATE_SUCCESS', 'FILTER_JOURNAL_TEXT_SUCCESS'
);